siteTitle = 'Sentimony Records'
siteDescr = 'Electronic Music Label'

siteBandcampUrl = 'https://sentimony.bandcamp.com'
siteSoundcloudUrl = 'https://soundcloud.com/sentimony'
siteFacebookUrl = 'https://www.facebook.com/sentimony.records'
siteDiscogsUrl = 'https://www.discogs.com/label/82598-Sentimony-Records'
siteTwitterUrl = 'https://twitter.com/sentimony'
siteGoogleplusUrl = ''
siteGithubUrl = 'https://github.com/sentimony'
siteYoutubeUrl = 'https://www.youtube.com/c/SentimonyRecords'

linkPrefix = "/sentimony-react"
